require 'railsless-deploy'          # gem install railsless-deploy
require 'didi/recipes/didi.rb'      # gem install capistrano-didi
load 'config/deploy'
require 'capistrano/ext/multistage' # gem install capistrano